version: '3.3'

services:
  # ---------- SERVICE LISYNC ----------- 
  lisync-service:
    container_name: serviceLisync
    image: giuliacarmona/lisync-app:latest
    networks:
     - my-bridge
    depends_on:
      - lisync-mysql
    command: ["java","-jar","JAR_Lisync.jar"]

  # ----------- MYSQL LISYNC ------------ 
  lisync-mysql:
    container_name: bancoLisync
    image: giuliacarmona/lisync-banco:latest
    environment:
      MYSQL_DATABASE: lisyncDB
      MYSQL_ROOT_PASSWORD: urubu100
    networks:
     - my-bridge
    ports:
      - 3306:3306

networks:
  my-bridge:
    driver: bridge